spring:
  application:
    name: stablematch

  datasource:
    url: jdbc:postgresql://postgres:5432/stablematch_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: kafka:29092

  cloud:
    function:
      definition: processMatch
    stream:
      kafka:
        binder:
          brokers: kafka:29092
      bindings:
        processMatch-in-0:
          destination: match-requests
          group: stablematch-group
        processMatch-out-0:
          destination: match-results
