server:
  port: 8091

spring:
  application:
    name: stablematch-service

algorithm:
  timeout-ms: 5000
  max-iterations: 1000

kafka:
  bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.yourpackage.stablematch: DEBUG
