
spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: processMatch
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        processMatch-in-0:
          destination: match-requests
          group: stablematch-group
        processMatch-out-0:
          destination: match-results
